#############################################################################
# Generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#  Mar 21, 2020 10:16:54 AM IST  platform: Windows NT
set vTcl(timestamp) ""


set image_list { \
    image21 "./logo.png" \
}
vTcl:create_project_images $image_list   ;# In image.tcl


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m44" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1190x746+241+98
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1444 881
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Hidden Query Extractor"
    vTcl:DefineAlias "$top" "HQE_OP" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    set site_3_0 $top.m44
    menu $site_3_0 \
        -activebackground SystemHighlight \
        -activeforeground SystemHighlightText \
        -background $vTcl(pr,menubgcolor) -font TkDefaultFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    canvas $top.can45 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 732 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground #c4c4c4 -selectforeground black -width 1173 
    vTcl:DefineAlias "$top.can45" "Canvas1" vTcl:WidgetProc "HQE_OP" 1
    set site_3_0 $top.can45
    frame $site_3_0.fra59 \
        -borderwidth 2 -relief groove -background #0080c0 -height 41 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 1170 
    vTcl:DefineAlias "$site_3_0.fra59" "Frame1_5" vTcl:WidgetProc "HQE_OP" 1
    set site_4_0 $site_3_0.fra59
    label $site_4_0.lab60 \
        -activebackground #f9f9f9 -activeforeground black -background #0080c0 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {HIDDEN QUERY} 
    vTcl:DefineAlias "$site_4_0.lab60" "Label1_3" vTcl:WidgetProc "HQE_OP" 1
    label $site_4_0.lab61 \
        -activebackground #f9f9f9 -activeforeground black -background #0080c0 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {EXTRACTED QUERY} 
    vTcl:DefineAlias "$site_4_0.lab61" "Label1_1" vTcl:WidgetProc "HQE_OP" 1
    place $site_4_0.lab60 \
        -in $site_4_0 -x 0 -relx 0.145 -y 0 -rely 0.238 -width 0 \
        -relwidth 0.233 -height 0 -relheight 0.571 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab61 \
        -in $site_4_0 -x 0 -relx 0.667 -y 0 -rely 0.238 -width 0 \
        -relwidth 0.239 -height 0 -relheight 0.571 -anchor nw \
        -bordermode ignore 
    ttk::style configure TSizegrip -background $vTcl(actual_gui_bg)
    vTcl::widgets::ttk::sizegrip::CreateCmd $site_3_0.tSi64 \
        -cursor size_nw_se 
    vTcl:DefineAlias "$site_3_0.tSi64" "TSizegrip1" vTcl:WidgetProc "HQE_OP" 1
    frame $site_3_0.fra65 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 76 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 1180 
    vTcl:DefineAlias "$site_3_0.fra65" "Frame2" vTcl:WidgetProc "HQE_OP" 1
    set site_4_0 $site_3_0.fra65
    button $site_4_0.but69 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #0080c0 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text FINISH 
    vTcl:DefineAlias "$site_4_0.but69" "finish" vTcl:WidgetProc "HQE_OP" 1
    button $site_4_0.but45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #0080c0 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {EXTRACTION TIME BREAKUP} 
    vTcl:DefineAlias "$site_4_0.but45" "extrac_breakup" vTcl:WidgetProc "HQE_OP" 1
    button $site_4_0.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #0080c0 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {SHOW MINIMIZED INSTANCE} 
    vTcl:DefineAlias "$site_4_0.but46" "show_min_ins" vTcl:WidgetProc "HQE_OP" 1
    place $site_4_0.but69 \
        -in $site_4_0 -x 0 -relx 0.828 -y 0 -rely 0.263 -width 179 \
        -relwidth 0 -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but45 \
        -in $site_4_0 -x 0 -relx 0.333 -y 0 -rely 0.263 -width 299 \
        -relwidth 0 -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but46 \
        -in $site_4_0 -x 0 -relx 0.017 -y 0 -rely 0.263 -width 299 \
        -relwidth 0 -height 44 -relheight 0 -anchor nw -bordermode ignore 
    ttk::separator $site_3_0.tSe70 \
        -orient vertical 
    vTcl:DefineAlias "$site_3_0.tSe70" "TSeparator1" vTcl:WidgetProc "HQE_OP" 1
    ttk::separator $site_3_0.tSe71 \
        -orient vertical 
    vTcl:DefineAlias "$site_3_0.tSe71" "TSeparator1_5" vTcl:WidgetProc "HQE_OP" 1
    label $site_3_0.lab44 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text SELECT 
    vTcl:DefineAlias "$site_3_0.lab44" "Label2_3" vTcl:WidgetProc "HQE_OP" 1
    label $site_3_0.lab45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text FROM 
    vTcl:DefineAlias "$site_3_0.lab45" "Label2_4" vTcl:WidgetProc "HQE_OP" 1
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text WHERE 
    vTcl:DefineAlias "$site_3_0.lab47" "Label2_5" vTcl:WidgetProc "HQE_OP" 1
    label $site_3_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {GROUP BY} 
    vTcl:DefineAlias "$site_3_0.lab48" "Label2_6" vTcl:WidgetProc "HQE_OP" 1
    label $site_3_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {ORDER BY} 
    vTcl:DefineAlias "$site_3_0.lab50" "Label2_7" vTcl:WidgetProc "HQE_OP" 1
    label $site_3_0.lab52 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text LIMIT 
    vTcl:DefineAlias "$site_3_0.lab52" "Label2_8" vTcl:WidgetProc "HQE_OP" 1
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_3_0.scr71 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.scr71" "selet_op_hid" vTcl:WidgetProc "HQE_OP" 1

    $site_3_0.scr71.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_3_0.scr73 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.scr73" "from_op_hid" vTcl:WidgetProc "HQE_OP" 1

    $site_3_0.scr73.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_3_0.scr74 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.scr74" "where_op_hid" vTcl:WidgetProc "HQE_OP" 1

    $site_3_0.scr74.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_3_0.scr75 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.scr75" "groupby_op_hid" vTcl:WidgetProc "HQE_OP" 1

    $site_3_0.scr75.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_3_0.scr76 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.scr76" "orderby_op_hid" vTcl:WidgetProc "HQE_OP" 1

    $site_3_0.scr76.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    entry $site_3_0.ent78 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground #0080c0 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 104 
    vTcl:DefineAlias "$site_3_0.ent78" "limit_op_hid" vTcl:WidgetProc "HQE_OP" 1
    button $site_3_0.but79 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #0080c0 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {RUN CHECKER} 
    vTcl:DefineAlias "$site_3_0.but79" "checker" vTcl:WidgetProc "HQE_OP" 1
    frame $site_3_0.fra44 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 95 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 1170 
    vTcl:DefineAlias "$site_3_0.fra44" "Frame1" vTcl:WidgetProc "HQE_OP" 1
    set site_4_0 $site_3_0.fra44
    message $site_4_0.mes46 \
        -background $vTcl(actual_gui_bg) -font {-family {Segoe UI} -size 12} \
        -foreground #800080 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {SAMPLE TEXT} -width 150 
    vTcl:DefineAlias "$site_4_0.mes46" "db_instance_msg" vTcl:WidgetProc "HQE_OP" 1
    label $site_4_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {DB Instance:} 
    vTcl:DefineAlias "$site_4_0.lab47" "Label2" vTcl:WidgetProc "HQE_OP" 1
    label $site_4_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Clauses With Syntactic Differences:} 
    vTcl:DefineAlias "$site_4_0.lab48" "Label2_1" vTcl:WidgetProc "HQE_OP" 1
    label $site_4_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Total Extraction Time:} 
    vTcl:DefineAlias "$site_4_0.lab49" "Label2_4" vTcl:WidgetProc "HQE_OP" 1
    label $site_4_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Number Of Executable Invocations:} 
    vTcl:DefineAlias "$site_4_0.lab50" "Label2_5" vTcl:WidgetProc "HQE_OP" 1
    message $site_4_0.mes51 \
        -background $vTcl(actual_gui_bg) -font {-family {Segoe UI} -size 12} \
        -foreground #800080 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {SAMPLE TEXT} -width 148 
    vTcl:DefineAlias "$site_4_0.mes51" "synt_diff_msg" vTcl:WidgetProc "HQE_OP" 1
    message $site_4_0.mes52 \
        -background $vTcl(actual_gui_bg) -font {-family {Segoe UI} -size 12} \
        -foreground #800080 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {SAMPLE TEXT} -width 119 
    vTcl:DefineAlias "$site_4_0.mes52" "tot_time_msg" vTcl:WidgetProc "HQE_OP" 1
    message $site_4_0.mes54 \
        -background $vTcl(actual_gui_bg) -font {-family {Segoe UI} -size 12} \
        -foreground #800080 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {SAMPLE TEXT} -width 119 
    vTcl:DefineAlias "$site_4_0.mes54" "num_invok_msg" vTcl:WidgetProc "HQE_OP" 1
    place $site_4_0.mes46 \
        -in $site_4_0 -x 0 -relx 0.094 -y 0 -rely 0.105 -width 0 \
        -relwidth 0.128 -height 0 -relheight 0.242 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab47 \
        -in $site_4_0 -x 0 -relx 0.009 -y 0 -rely 0.105 -width 0 \
        -relwidth 0.082 -height 0 -relheight 0.221 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab48 \
        -in $site_4_0 -x 0 -relx 0.009 -y 0 -rely 0.526 -width 0 \
        -relwidth 0.236 -height 0 -relheight 0.221 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab49 \
        -in $site_4_0 -x 0 -relx 0.726 -y 0 -rely 0.105 -width 0 \
        -relwidth 0.167 -height 0 -relheight 0.221 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab50 \
        -in $site_4_0 -x 0 -relx 0.64 -y 0 -rely 0.632 -width 0 \
        -relwidth 0.254 -height 0 -relheight 0.221 -anchor nw \
        -bordermode ignore 
    place $site_4_0.mes51 \
        -in $site_4_0 -x 0 -relx 0.248 -y 0 -rely 0.526 -width 0 \
        -relwidth 0.126 -height 0 -relheight 0.242 -anchor nw \
        -bordermode ignore 
    place $site_4_0.mes52 \
        -in $site_4_0 -x 0 -relx 0.888 -y 0 -rely 0.105 -width 0 \
        -relwidth 0.102 -height 0 -relheight 0.242 -anchor nw \
        -bordermode ignore 
    place $site_4_0.mes54 \
        -in $site_4_0 -x 0 -relx 0.888 -y 0 -rely 0.632 -width 0 \
        -relwidth 0.102 -height 0 -relheight 0.242 -anchor nw \
        -bordermode ignore 
    label $site_3_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text SELECT 
    vTcl:DefineAlias "$site_3_0.lab49" "Label2_4" vTcl:WidgetProc "HQE_OP" 1
    label $site_3_0.lab51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text FROM 
    vTcl:DefineAlias "$site_3_0.lab51" "Label2_6" vTcl:WidgetProc "HQE_OP" 1
    label $site_3_0.lab53 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text WHERE 
    vTcl:DefineAlias "$site_3_0.lab53" "Label2_5" vTcl:WidgetProc "HQE_OP" 1
    label $site_3_0.lab54 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {GROUP BY} 
    vTcl:DefineAlias "$site_3_0.lab54" "Label2_6" vTcl:WidgetProc "HQE_OP" 1
    label $site_3_0.lab55 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {ORDER BY} 
    vTcl:DefineAlias "$site_3_0.lab55" "Label2_7" vTcl:WidgetProc "HQE_OP" 1
    label $site_3_0.lab56 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text LIMIT 
    vTcl:DefineAlias "$site_3_0.lab56" "Label2_9" vTcl:WidgetProc "HQE_OP" 1
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_3_0.scr58 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.scr58" "select_op_eq" vTcl:WidgetProc "HQE_OP" 1

    $site_3_0.scr58.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_3_0.scr59 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.scr59" "from_op_eq" vTcl:WidgetProc "HQE_OP" 1

    $site_3_0.scr59.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_3_0.scr60 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.scr60" "where_op_eq" vTcl:WidgetProc "HQE_OP" 1

    $site_3_0.scr60.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_3_0.scr61 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.scr61" "groupby_op_eq" vTcl:WidgetProc "HQE_OP" 1

    $site_3_0.scr61.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_3_0.scr62 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.scr62" "orderby_op_eq" vTcl:WidgetProc "HQE_OP" 1

    $site_3_0.scr62.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    entry $site_3_0.ent63 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground #0080c0 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 104 
    vTcl:DefineAlias "$site_3_0.ent63" "limit_op_eq" vTcl:WidgetProc "HQE_OP" 1
    button $site_3_0.but45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -borderwidth 0 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image image21 -pady 0 -text Button 
    vTcl:DefineAlias "$site_3_0.but45" "Button2" vTcl:WidgetProc "HQE_OP" 1
    place $site_3_0.fra59 \
        -in $site_3_0 -x 0 -y 0 -rely 0.06 -width 0 -relwidth 0.997 -height 0 \
        -relheight 0.053 -anchor nw -bordermode ignore 
    place $site_3_0.tSi64 \
        -in $site_3_0 -x 0 -relx 1 -y 0 -rely 1 -anchor se -bordermode inside 
    place $site_3_0.fra65 \
        -in $site_3_0 -x 0 -relx 0.002 -y 0 -rely 0.888 -width 0 \
        -relwidth 0.997 -height 0 -relheight 0.104 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tSe70 \
        -in $site_3_0 -x 0 -relx 0.494 -y 0 -rely 0.109 -height 0 \
        -relheight 0.637 -anchor nw -bordermode inside 
    place $site_3_0.tSe71 \
        -in $site_3_0 -x 0 -relx 0.503 -y 0 -rely 0.109 -width 0 \
        -relwidth 0.002 -height 0 -relheight 0.637 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab44 \
        -in $site_3_0 -x 0 -relx 0.06 -y 0 -rely 0.191 -width 0 \
        -relwidth 0.066 -height 0 -relheight 0.025 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 0 -relx 0.06 -y 0 -rely 0.273 -width 0 \
        -relwidth 0.067 -height 0 -relheight 0.025 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.06 -y 0 -rely 0.396 -width 0 \
        -relwidth 0.066 -height 0 -relheight 0.025 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.051 -y 0 -rely 0.533 -width 0 \
        -relwidth 0.066 -height 0 -relheight 0.025 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -relx 0.051 -y 0 -rely 0.615 -width 0 \
        -relwidth 0.067 -height 0 -relheight 0.025 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 0 -relx 0.068 -y 0 -rely 0.683 -width 0 \
        -relwidth 0.066 -height 0 -relheight 0.026 -anchor nw \
        -bordermode ignore 
    place $site_3_0.scr71 \
        -in $site_3_0 -x 0 -relx 0.128 -y 0 -rely 0.178 -width 0 \
        -relwidth 0.362 -height 0 -relheight 0.048 -anchor nw \
        -bordermode ignore 
    place $site_3_0.scr73 \
        -in $site_3_0 -x 0 -relx 0.128 -y 0 -rely 0.26 -width 0 \
        -relwidth 0.362 -height 0 -relheight 0.048 -anchor nw \
        -bordermode ignore 
    place $site_3_0.scr74 \
        -in $site_3_0 -x 0 -relx 0.128 -y 0 -rely 0.342 -width 0 \
        -relwidth 0.361 -height 0 -relheight 0.142 -anchor nw \
        -bordermode ignore 
    place $site_3_0.scr75 \
        -in $site_3_0 -x 0 -relx 0.128 -y 0 -rely 0.519 -width 0 \
        -relwidth 0.362 -height 0 -relheight 0.048 -anchor nw \
        -bordermode ignore 
    place $site_3_0.scr76 \
        -in $site_3_0 -x 0 -relx 0.128 -y 0 -rely 0.601 -width 0 \
        -relwidth 0.361 -height 0 -relheight 0.048 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent78 \
        -in $site_3_0 -x 0 -relx 0.128 -y 0 -rely 0.683 -width 104 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but79 \
        -in $site_3_0 -x 0 -relx 0.647 -y 0 -rely 0.915 -width 149 \
        -relwidth 0 -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra44 \
        -in $site_3_0 -x 0 -relx 0.002 -y 0 -rely 0.751 -width 0 \
        -relwidth 0.997 -height 0 -relheight 0.13 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.571 -y 0 -rely 0.191 -width 0 \
        -relwidth 0.066 -height 0 -relheight 0.026 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.571 -y 0 -rely 0.26 -width 0 \
        -relwidth 0.066 -height 0 -relheight 0.025 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -relx 0.571 -y 0 -rely 0.396 -width 0 \
        -relwidth 0.066 -height 0 -relheight 0.026 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 0 -relx 0.562 -y 0 -rely 0.533 -width 0 \
        -relwidth 0.066 -height 0 -relheight 0.025 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 0 -relx 0.562 -y 0 -rely 0.615 -width 0 \
        -relwidth 0.067 -height 0 -relheight 0.025 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 0 -relx 0.579 -y 0 -rely 0.683 -width 0 \
        -relwidth 0.066 -height 0 -relheight 0.026 -anchor nw \
        -bordermode ignore 
    place $site_3_0.scr58 \
        -in $site_3_0 -x 0 -relx 0.639 -y 0 -rely 0.178 -width 0 \
        -relwidth 0.354 -height 0 -relheight 0.048 -anchor nw \
        -bordermode ignore 
    place $site_3_0.scr59 \
        -in $site_3_0 -x 0 -relx 0.639 -y 0 -rely 0.26 -width 0 \
        -relwidth 0.354 -height 0 -relheight 0.048 -anchor nw \
        -bordermode ignore 
    place $site_3_0.scr60 \
        -in $site_3_0 -x 0 -relx 0.639 -y 0 -rely 0.342 -width 0 \
        -relwidth 0.354 -height 0 -relheight 0.143 -anchor nw \
        -bordermode ignore 
    place $site_3_0.scr61 \
        -in $site_3_0 -x 0 -relx 0.639 -y 0 -rely 0.519 -width 0 \
        -relwidth 0.354 -height 0 -relheight 0.048 -anchor nw \
        -bordermode ignore 
    place $site_3_0.scr62 \
        -in $site_3_0 -x 0 -relx 0.639 -y 0 -rely 0.601 -width 0 \
        -relwidth 0.354 -height 0 -relheight 0.048 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent63 \
        -in $site_3_0 -x 0 -relx 0.639 -y 0 -rely 0.683 -width 104 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but45 \
        -in $site_3_0 -x 0 -relx 0.422 -y 0 -rely 0.012 -width 207 \
        -relwidth 0 -height 34 -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.can45 \
        -in $top -x 0 -relx 0.008 -y 0 -rely 0.013 -width 0 -relwidth 0.987 \
        -height 0 -relheight 0.981 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

