#############################################################################
# Generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#  Mar 21, 2020 10:15:24 AM IST  platform: Windows NT
set vTcl(timestamp) ""


set image_list { \
    image20 "./logo.png" \
}
vTcl:create_project_images $image_list   ;# In image.tcl


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m44" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1190x746+241+98
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1444 881
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Hidden Query Extractor"
    vTcl:DefineAlias "$top" "HQE" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    set site_3_0 $top.m44
    menu $site_3_0 \
        -activebackground SystemHighlight \
        -activeforeground SystemHighlightText \
        -background $vTcl(pr,menubgcolor) -font TkDefaultFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    canvas $top.can45 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 732 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground #c4c4c4 -selectforeground black -width 1173 
    vTcl:DefineAlias "$top.can45" "Canvas1" vTcl:WidgetProc "HQE" 1
    set site_3_0 $top.can45
    frame $site_3_0.fra47 \
        -borderwidth 2 -relief groove -background #0080c0 -height 42 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 1170 
    vTcl:DefineAlias "$site_3_0.fra47" "Frame1" vTcl:WidgetProc "HQE" 1
    label $site_3_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black -background #0080c0 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {DATABASE CONNECTIVITY} 
    vTcl:DefineAlias "$site_3_0.lab49" "Label1_1" vTcl:WidgetProc "HQE" 1
    label $site_3_0.lab51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {DB Engine} 
    vTcl:DefineAlias "$site_3_0.lab51" "Label2" vTcl:WidgetProc "HQE" 1
    label $site_3_0.lab53 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {DB Instance} 
    vTcl:DefineAlias "$site_3_0.lab53" "Label2_3" vTcl:WidgetProc "HQE" 1
    label $site_3_0.lab54 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Connection Parameters} 
    vTcl:DefineAlias "$site_3_0.lab54" "Label2_4" vTcl:WidgetProc "HQE" 1
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_3_0.scr57 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.scr57" "conn_param" vTcl:WidgetProc "HQE" 1

    $site_3_0.scr57.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    frame $site_3_0.fra59 \
        -borderwidth 2 -relief groove -background #0080c0 -height 41 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 1170 
    vTcl:DefineAlias "$site_3_0.fra59" "Frame1_5" vTcl:WidgetProc "HQE" 1
    set site_4_0 $site_3_0.fra59
    label $site_4_0.lab60 \
        -activebackground #f9f9f9 -activeforeground black -background #0080c0 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {DIRECT HIDDEN QUERY INPUT} 
    vTcl:DefineAlias "$site_4_0.lab60" "Label1_2" vTcl:WidgetProc "HQE" 1
    label $site_4_0.lab61 \
        -activebackground #f9f9f9 -activeforeground black -background #0080c0 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {EXTERNAL EXECUTABLE INPUT} 
    vTcl:DefineAlias "$site_4_0.lab61" "Label1_1" vTcl:WidgetProc "HQE" 1
    place $site_4_0.lab60 \
        -in $site_4_0 -x 0 -relx 0.111 -y 0 -rely 0.244 -width 0 \
        -relwidth 0.233 -height 0 -relheight 0.561 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab61 \
        -in $site_4_0 -x 0 -relx 0.632 -y 0 -rely 0.244 -width 0 \
        -relwidth 0.24 -height 0 -relheight 0.561 -anchor nw \
        -bordermode ignore 
    ttk::style configure TSizegrip -background $vTcl(actual_gui_bg)
    vTcl::widgets::ttk::sizegrip::CreateCmd $site_3_0.tSi64 \
        -cursor size_nw_se 
    vTcl:DefineAlias "$site_3_0.tSi64" "TSizegrip1" vTcl:WidgetProc "HQE" 1
    frame $site_3_0.fra65 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 1156 
    vTcl:DefineAlias "$site_3_0.fra65" "Frame2" vTcl:WidgetProc "HQE" 1
    set site_4_0 $site_3_0.fra65
    checkbutton $site_4_0.che67 \
        -activebackground #d9d9d9 -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Save Extracted Query} -variable che67 
    vTcl:DefineAlias "$site_4_0.che67" "save_checkbox" vTcl:WidgetProc "HQE" 1
    button $site_4_0.but69 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #0080c0 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {RUN reveal} 
    vTcl:DefineAlias "$site_4_0.but69" "run_reveal" vTcl:WidgetProc "HQE" 1
    button $site_4_0.but63 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #0080c0 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10} -foreground #ffffff -height 31 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Browse 
    vTcl:DefineAlias "$site_4_0.but63" "browse" vTcl:WidgetProc "HQE" 1
    place $site_4_0.che67 \
        -in $site_4_0 -x 0 -relx 0.026 -y 0 -rely 0.4 -height 0 \
        -relheight 0.333 -anchor nw -bordermode ignore 
    place $site_4_0.but69 \
        -in $site_4_0 -x 0 -relx 0.83 -y 0 -rely 0.267 -width 179 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but63 \
        -in $site_4_0 -x 0 -relx 0.686 -y 0 -rely 0.395 -width 57 -relwidth 0 \
        -height 31 -relheight 0 -anchor nw -bordermode ignore 
    entry $site_3_0.ent68 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground #800000 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 574 
    vTcl:DefineAlias "$site_3_0.ent68" "save_output" vTcl:WidgetProc "HQE" 1
    ttk::separator $site_3_0.tSe70 \
        -orient vertical 
    vTcl:DefineAlias "$site_3_0.tSe70" "TSeparator1" vTcl:WidgetProc "HQE" 1
    ttk::separator $site_3_0.tSe71 \
        -orient vertical 
    vTcl:DefineAlias "$site_3_0.tSe71" "TSeparator1_5" vTcl:WidgetProc "HQE" 1
    label $site_3_0.lab44 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text SELECT 
    vTcl:DefineAlias "$site_3_0.lab44" "Label2_2" vTcl:WidgetProc "HQE" 1
    label $site_3_0.lab45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text FROM 
    vTcl:DefineAlias "$site_3_0.lab45" "Label2_2" vTcl:WidgetProc "HQE" 1
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text WHERE 
    vTcl:DefineAlias "$site_3_0.lab47" "Label2_5" vTcl:WidgetProc "HQE" 1
    label $site_3_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {GROUP BY} 
    vTcl:DefineAlias "$site_3_0.lab48" "Label2_6" vTcl:WidgetProc "HQE" 1
    label $site_3_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {ORDER BY} 
    vTcl:DefineAlias "$site_3_0.lab50" "Label2_7" vTcl:WidgetProc "HQE" 1
    label $site_3_0.lab52 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text LIMIT 
    vTcl:DefineAlias "$site_3_0.lab52" "Label2_8" vTcl:WidgetProc "HQE" 1
    label $site_3_0.lab55 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Stored Procedure Name} 
    vTcl:DefineAlias "$site_3_0.lab55" "Label2_3" vTcl:WidgetProc "HQE" 1
    label $site_3_0.lab56 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {File Path} 
    vTcl:DefineAlias "$site_3_0.lab56" "Label2_4" vTcl:WidgetProc "HQE" 1
    label $site_3_0.lab61 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Execution Command} 
    vTcl:DefineAlias "$site_3_0.lab61" "Label2_5" vTcl:WidgetProc "HQE" 1
    radiobutton $site_3_0.rad62 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Stored Procedure} -value 0 
    vTcl:DefineAlias "$site_3_0.rad62" "stored_proc_radio" vTcl:WidgetProc "HQE" 1
    entry $site_3_0.ent63 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground #0080c0 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 234 
    vTcl:DefineAlias "$site_3_0.ent63" "stored_proc_inp" vTcl:WidgetProc "HQE" 1
    radiobutton $site_3_0.rad64 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Imperative Exeutable} -value 1 
    vTcl:DefineAlias "$site_3_0.rad64" "imp_exec_radio" vTcl:WidgetProc "HQE" 1
    entry $site_3_0.ent65 \
        -background white -disabledbackground #c0c0c0 \
        -disabledforeground #c0c0c0 -font TkFixedFont -foreground #0080c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -state disabled -width 234 
    vTcl:DefineAlias "$site_3_0.ent65" "file_path" vTcl:WidgetProc "HQE" 1
    entry $site_3_0.ent66 \
        -background white -disabledbackground #c0c0c0 \
        -disabledforeground #a3a3a3 -font TkFixedFont -foreground #0080c0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -state disabled -width 234 
    vTcl:DefineAlias "$site_3_0.ent66" "exec_command" vTcl:WidgetProc "HQE" 1
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_3_0.scr71 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.scr71" "selet_inp" vTcl:WidgetProc "HQE" 1

    $site_3_0.scr71.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_3_0.scr73 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.scr73" "from_inp" vTcl:WidgetProc "HQE" 1

    $site_3_0.scr73.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_3_0.scr74 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.scr74" "where_inp" vTcl:WidgetProc "HQE" 1

    $site_3_0.scr74.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_3_0.scr75 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.scr75" "groupby_inp" vTcl:WidgetProc "HQE" 1

    $site_3_0.scr75.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_3_0.scr76 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.scr76" "orderby_inp" vTcl:WidgetProc "HQE" 1

    $site_3_0.scr76.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    entry $site_3_0.ent78 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground #0080c0 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 104 
    vTcl:DefineAlias "$site_3_0.ent78" "limit_inp" vTcl:WidgetProc "HQE" 1
    button $site_3_0.but79 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #0080c0 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {HIDE QUERY} 
    vTcl:DefineAlias "$site_3_0.but79" "hide_query" vTcl:WidgetProc "HQE" 1
    ttk::combobox $site_3_0.tCo51 \
        -font {-family {Segoe UI} -size 11 -weight bold} -state readonly \
        -textvariable combobox -foreground #0080c0 -background {} \
        -takefocus {} -cursor hand2 
    vTcl:DefineAlias "$site_3_0.tCo51" "db_engine" vTcl:WidgetProc "HQE" 1
    ttk::combobox $site_3_0.tCo52 \
        -font {-family {Segoe UI} -size 11 -weight bold} \
        -textvariable combobox -foreground #0080c0 -background {} \
        -takefocus {} -cursor hand2 
    vTcl:DefineAlias "$site_3_0.tCo52" "db_instance" vTcl:WidgetProc "HQE" 1
    button $site_3_0.but44 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -borderwidth 0 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image image20 -pady 0 -text Button 
    vTcl:DefineAlias "$site_3_0.but44" "Button1" vTcl:WidgetProc "HQE" 1
    place $site_3_0.fra47 \
        -in $site_3_0 -x 0 -y 0 -rely 0.06 -width 0 -relwidth 0.997 -height 0 \
        -relheight 0.053 -anchor nw -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.392 -y 0 -rely 0.069 -width 0 \
        -relwidth 0.216 -height 0 -relheight 0.032 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.043 -y 0 -rely 0.137 -width 0 \
        -relwidth 0.067 -height 0 -relheight 0.025 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -relx 0.426 -y 0 -rely 0.137 -width 0 \
        -relwidth 0.073 -height 0 -relheight 0.026 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 0 -relx 0.622 -y 0 -rely 0.137 -width 0 \
        -relwidth 0.158 -height 0 -relheight 0.025 -anchor nw \
        -bordermode ignore 
    place $site_3_0.scr57 \
        -in $site_3_0 -x 0 -relx 0.784 -y 0 -rely 0.123 -width 0 \
        -relwidth 0.182 -height 0 -relheight 0.072 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra59 \
        -in $site_3_0 -x 0 -relx 0.001 -y 0 -rely 0.208 -width 0 \
        -relwidth 0.997 -height 0 -relheight 0.057 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tSi64 \
        -in $site_3_0 -x 0 -relx 1 -y 0 -rely 1 -anchor se -bordermode inside 
    place $site_3_0.fra65 \
        -in $site_3_0 -x 0 -relx 0.009 -y 0 -rely 0.886 -width 0 \
        -relwidth 0.986 -height 0 -relheight 0.104 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent68 \
        -in $site_3_0 -x 0 -relx 0.196 -y 0 -rely 0.928 -width 574 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tSe70 \
        -in $site_3_0 -x 0 -relx 0.503 -y 0 -rely 0.26 -height 0 \
        -relheight 0.623 -anchor nw -bordermode inside 
    place $site_3_0.tSe71 \
        -in $site_3_0 -x 0 -relx 0.511 -y 0 -rely 0.26 -width 0 \
        -relwidth 0.002 -height 0 -relheight 0.623 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab44 \
        -in $site_3_0 -x 0 -relx 0.06 -y 0 -rely 0.314 -width 0 \
        -relwidth 0.066 -height 0 -relheight 0.025 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 0 -relx 0.06 -y 0 -rely 0.383 -width 0 \
        -relwidth 0.067 -height 0 -relheight 0.025 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.06 -y 0 -rely 0.478 -width 0 \
        -relwidth 0.066 -height 0 -relheight 0.025 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.051 -y 0 -rely 0.587 -width 0 \
        -relwidth 0.066 -height 0 -relheight 0.025 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -relx 0.051 -y 0 -rely 0.669 -width 0 \
        -relwidth 0.067 -height 0 -relheight 0.025 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 0 -relx 0.068 -y 0 -rely 0.751 -width 0 \
        -relwidth 0.066 -height 0 -relheight 0.026 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 0 -relx 0.579 -y 0 -rely 0.383 -width 0 \
        -relwidth 0.16 -height 0 -relheight 0.025 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 0 -relx 0.63 -y 0 -rely 0.56 -width 0 \
        -relwidth 0.066 -height 0 -relheight 0.025 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab61 \
        -in $site_3_0 -x 0 -relx 0.562 -y 0 -rely 0.656 -width 0 \
        -relwidth 0.143 -height 0 -relheight 0.025 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad62 \
        -in $site_3_0 -x 0 -relx 0.545 -y 0 -rely 0.314 -height 0 \
        -relheight 0.034 -anchor nw -bordermode ignore 
    place $site_3_0.ent63 \
        -in $site_3_0 -x 0 -relx 0.758 -y 0 -rely 0.383 -width 234 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad64 \
        -in $site_3_0 -x 0 -relx 0.545 -y 0 -rely 0.478 -height 0 \
        -relheight 0.034 -anchor nw -bordermode ignore 
    place $site_3_0.ent65 \
        -in $site_3_0 -x 0 -relx 0.758 -y 0 -rely 0.546 -width 234 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent66 \
        -in $site_3_0 -x 0 -relx 0.758 -y 0 -rely 0.656 -width 234 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.scr71 \
        -in $site_3_0 -x 0 -relx 0.128 -y 0 -rely 0.301 -width 0 \
        -relwidth 0.362 -height 0 -relheight 0.048 -anchor nw \
        -bordermode ignore 
    place $site_3_0.scr73 \
        -in $site_3_0 -x 0 -relx 0.128 -y 0 -rely 0.369 -width 0 \
        -relwidth 0.362 -height 0 -relheight 0.048 -anchor nw \
        -bordermode ignore 
    place $site_3_0.scr74 \
        -in $site_3_0 -x 0 -relx 0.128 -y 0 -rely 0.423 -width 0 \
        -relwidth 0.361 -height 0 -relheight 0.142 -anchor nw \
        -bordermode ignore 
    place $site_3_0.scr75 \
        -in $site_3_0 -x 0 -relx 0.128 -y 0 -rely 0.574 -width 0 \
        -relwidth 0.362 -height 0 -relheight 0.048 -anchor nw \
        -bordermode ignore 
    place $site_3_0.scr76 \
        -in $site_3_0 -x 0 -relx 0.128 -y 0 -rely 0.656 -width 0 \
        -relwidth 0.361 -height 0 -relheight 0.048 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent78 \
        -in $site_3_0 -x 0 -relx 0.128 -y 0 -rely 0.738 -width 104 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but79 \
        -in $site_3_0 -x 0 -relx 0.366 -y 0 -rely 0.806 -width 149 \
        -relwidth 0 -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCo51 \
        -in $site_3_0 -x 0 -relx 0.119 -y 0 -rely 0.137 -width 0 \
        -relwidth 0.285 -height 0 -relheight 0.044 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo52 \
        -in $site_3_0 -x 0 -relx 0.503 -y 0 -rely 0.137 -width 0 \
        -relwidth 0.122 -height 0 -relheight 0.044 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but44 \
        -in $site_3_0 -x 0 -relx 0.429 -y 0 -rely 0.012 -width 207 \
        -relwidth 0 -height 34 -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.can45 \
        -in $top -x 0 -relx 0.008 -y 0 -rely 0.013 -width 0 -relwidth 0.987 \
        -height 0 -relheight 0.981 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

