#############################################################################
# Generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#  Mar 22, 2020 07:43:43 PM IST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 1159x728+262+100
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1444 881
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Miniscule Database Instance(s)"
    vTcl:DefineAlias "$top" "showdata" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    canvas $top.can51 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 713 -insertbackground black -relief ridge \
        -selectbackground #c4c4c4 -selectforeground black -width 1153 
    vTcl:DefineAlias "$top.can51" "Canvas1" vTcl:WidgetProc "showdata" 1
    set site_3_0 $top.can51
    frame $site_3_0.fra52 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 45 -width 1135 
    vTcl:DefineAlias "$site_3_0.fra52" "Frame1" vTcl:WidgetProc "showdata" 1
    set site_4_0 $site_3_0.fra52
    ttk::combobox $site_4_0.tCo53 \
        -font {-family {Segoe UI} -size 11} -textvariable combobox \
        -foreground #0080c0 -background {} -takefocus {} 
    vTcl:DefineAlias "$site_4_0.tCo53" "tableSelection" vTcl:WidgetProc "showdata" 1
    ttk::combobox $site_4_0.tCo54 \
        -font {-family {Segoe UI} -size 11} -textvariable combobox \
        -foreground #0080c0 -background {} -takefocus {} 
    vTcl:DefineAlias "$site_4_0.tCo54" "attribSelection" vTcl:WidgetProc "showdata" 1
    label $site_4_0.lab56 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -justify right -text {Select Table} 
    vTcl:DefineAlias "$site_4_0.lab56" "Label1" vTcl:WidgetProc "showdata" 1
    ttk::combobox $site_4_0.tCo59 \
        -font {-family {Segoe UI} -size 11} -textvariable combobox \
        -foreground #0080c0 -background {} -takefocus {} 
    vTcl:DefineAlias "$site_4_0.tCo59" "InstanceSelection" vTcl:WidgetProc "showdata" 1
    vTcl:copy_lock $site_4_0.tCo59
    label $site_4_0.lab61 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify right -text {Select Instance Number} 
    vTcl:DefineAlias "$site_4_0.lab61" "Label1_4" vTcl:WidgetProc "showdata" 1
    place $site_4_0.tCo53 \
        -in $site_4_0 -x 0 -relx 0.132 -y 0 -rely 0.182 -width 0 \
        -relwidth 0.126 -height 0 -relheight 0.618 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tCo54 \
        -in $site_4_0 -x 0 -relx 0.485 -y 0 -rely 0.182 -width 0 \
        -relwidth 0.128 -height 0 -relheight 0.618 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab56 \
        -in $site_4_0 -x 0 -relx 0.035 -y 0 -rely 0.182 -width 0 \
        -relwidth 0.093 -height 0 -relheight 0.564 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tCo59 \
        -in $site_4_0 -x 0 -relx 0.855 -y 0 -rely 0.182 -width 0 \
        -relwidth 0.129 -height 0 -relheight 0.618 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab61 \
        -in $site_4_0 -x 0 -relx 0.678 -y 0 -rely 0.182 -width 0 \
        -relwidth 0.17 -height 0 -relheight 0.564 -anchor nw \
        -bordermode ignore 
    label $site_3_0.lab60 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify right -text {Select Attribute} 
    vTcl:DefineAlias "$site_3_0.lab60" "Label1_3" vTcl:WidgetProc "showdata" 1
    frame $site_3_0.fra62 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 595 -width 1136 
    vTcl:DefineAlias "$site_3_0.fra62" "tableContainer" vTcl:WidgetProc "showdata" 1
    button $site_3_0.but63 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -borderwidth 0 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Button 
    vTcl:DefineAlias "$site_3_0.but63" "Button1" vTcl:WidgetProc "showdata" 1
    place $site_3_0.fra52 \
        -in $site_3_0 -x 0 -relx 0.009 -y 0 -rely 0.084 -width 0 \
        -relwidth 0.984 -height 0 -relheight 0.063 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 0 -relx 0.356 -y 0 -rely 0.098 -width 0 \
        -relwidth 0.124 -height 0 -relheight 0.029 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra62 \
        -in $site_3_0 -x 0 -relx 0.009 -y 0 -rely 0.154 -width 0 \
        -relwidth 0.985 -height 0 -relheight 0.835 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but63 \
        -in $site_3_0 -x 0 -relx 0.416 -y 0 -rely 0.014 -width 197 \
        -relwidth 0 -height 44 -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.can51 \
        -in $top -x 0 -y 0 -rely 0.014 -width 0 -relwidth 0.995 -height 0 \
        -relheight 0.979 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

